src/objects/Email_Object__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Email_Objects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Attachment__c</fullName>
        <description>This is created to store the attachment id of the email content</description>
        <label>Attachment</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email_Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Message_Type__c</fullName>
        <label>Email Message Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single Email</fullName>
                </value>
                <value>
                    <fullName>Mass Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Status__c</fullName>
        <label>Email Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent Email</fullName>
                </value>
                <value>
                    <fullName>Replied Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Subject__c</fullName>
        <label>Email_Subject</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReplyEmailContenetPdf__c</fullName>
        <label>ReplyEmailContenetPdf</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Email Tracking</label>
    <nameField>
        <displayFormat>ET-{00000000}</displayFormat>
        <label>Email_Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ReplyEmailHandlerMass.cls
global class ReplyEmailHandlerMass implements Messaging.InboundEmailHandler {
    
    //Getting Inbound Email
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
    system.debug('>>>>> '+email.fromAddress);
    Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
    Email_Object__c feedback= new Email_Object__c ();
    feedback.Account__c =[SELECT Id FROM Account WHERE Account_Official_Email__c= :email.fromAddress OR Account_Personal_Email__c= :email.fromAddress    LIMIT 1].id;
    feedback.Email_Body__c =   email.plainTextBody;
    feedback.Email_Message_Type__c='Mass Email';
    feedback.Email_Status__c='Replied Email';
    feedback.Email_Subject__c=email.subject;
    
    try{
    blob b = blob.toPDF(email.plainTextBody);
     Attachment attachment = new Attachment();
             
              attachment.Name =''+system.now()+'.pdf';
              attachment.Body = b;
              attachment.ParentId = feedback.Account__c;
              insert attachment;
    feedback.ReplyEmailContenetPdf__c = attachment.id;
    }catch(Exception ex){
    
    System.debug('>>>>> exception '+ex);
    }
    
    if(email.textAttachments != null)
        {
            // Save attachments, if any
            for (Messaging.Inboundemail.TextAttachment tAttachment : email.textAttachments) {
              Attachment attachment = new Attachment();
             
              attachment.Name = tAttachment.fileName;
              attachment.Body = Blob.valueOf(tAttachment.body);
              attachment.ParentId = feedback.Account__c;
              insert attachment;
              feedback.Attachment__c=attachment.id;
            }
        }
        
          if(email.binaryAttachments != null)
        {
            for (Messaging.Inboundemail.BinaryAttachment bAttachment : email.binaryAttachments) {
              Attachment attachment = new Attachment();
             
              attachment.Name = bAttachment.fileName;
              attachment.Body = bAttachment.body;
              attachment.ParentId = feedback.Account__c;
              insert attachment;
              feedback.Attachment__c=attachment.id;
            }
        }
    
    insert feedback;
    return result;
    
}
}