src/objects/Email_Tracking__c.object
<CustomObject>
    <description>This object is created to track emails on Opportunities</description>
    <fields>
        <fullName>Attachment__c</fullName>
        <description>This field is used to store the attachment id</description>
        <label>Attachment</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email_Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Subject__c</fullName>
        <label>Email Subject</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Type__c</fullName>
        <label>Email Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personal Email</fullName>
                </value>
                <value>
                    <fullName>Work Email</fullName>
                </value>
                <value>
                    <fullName>--None--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Email Trackings</relationshipLabel>
        <relationshipName>Email_Trackings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Email Tracking</label>
    <nameField>
        <displayFormat>ETOP-{0000}</displayFormat>
        <label>Email Tracking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestSingleEmailLeadcontroller.cls
@isTest(SeeAllData=true) 
    public class TestSingleEmailLeadcontroller{
    public static testMethod void testPositive() {
    Test.StartTest();
    //create Lead
    Lead lead = New Lead();
    lead.FirstName ='FNAME';
    lead.LastName ='LnNAME';
    lead.Company='LEAD COMPANY';
    //lead.Type__c='Retirement Plan';  
    lead.Type__c=' Non-Retirement Plan ';
    lead.email='test.e@test.com';
    //List<Schema.PicklistEntry> ple = Schema.getGlobalDescribe().get('Lead').getDescribe().fields.getMap().get('Type').getDescribe().getPicklistValues();
   // String s =String.Valueof(ple);
    //if(s.contains('Both'))
   // {lead.Type__c=s;}
    insert lead;
    
    //Insert Attachment
    Attachment attachment =new Attachment();
    attachment.ParentId=lead.id;
    attachment.Name='dummy.txt';
    attachment.body=Blob.valueOf('Unit Test Attachment Body');
    insert attachment;
    
    
    //insert EmailTrackingObject
    Email_Tracking__c  emailObj1 = new Email_Tracking__c();
    emailObj1.Email_Type__c='--None--';
    emailObj1.lead__c=lead.id;
    emailObj1.Attachment__c=String.valueOf(attachment.Id);
    insert emailObj1;
    
    Apexpages.StandardController stdController = new Apexpages.StandardController(lead);  
    SingleEmailLeadcontroller controller= new   SingleEmailLeadcontroller(stdController);
    
    PageReference pageRef = Page.SendEmailOnOpportunity;
    pageRef.getParameters().put('id', String.valueOf(lead.Id));
    system.Test.setCurrentPage(pageRef);
        controller.emailObj.Email_Subject__c = 'test';
        controller.emailObj.Email_Body__c = 'test';
       controller.lead=lead;
       controller.AttachmentId=attachment.Id;
       controller.emailSubject='test subject';
       controller.emailBody='test body';
       controller.strImageBlob='str';
       controller.renderPeronsal=true;
       controller.renderwork=true;
       controller.emailObj=emailObj1;
       controller.getItems();
       controller.contentType ='application/vnd.oasis.opendocument.text';
       controller.dosubmit();
       controller.showEmail();
       controller.upload();
       
       try{
       controller.sendEmail();
       
       }catch(Exception ex){}
    
    Test.StopTest();   
    
    SingleEmailLeadcontroller ss =new  SingleEmailLeadcontroller();
    }
    
   /* public static testMethod void testPersonalEmail() {
    Test.StartTest();
    //create Lead
    Lead lead = New Lead();
    lead.Type__c='Retirement Plan';  
    insert lead;
    
    //Insert Attachment
    Attachment attachment =new Attachment();
    attachment.ParentId=lead.id;
    attachment.Name='dummy.txt';
    attachment.body=Blob.valueOf('Unit Test Attachment Body');
    insert attachment;
    
    
    //insert EmailTrackingObject
    Email_Tracking__c  emailObj1 = new Email_Tracking__c();
    emailObj1.Email_Type__c='Personal Email';
    emailObj1.lead__c=lead.id;
    emailObj1.Attachment__c=String.valueOf(attachment.Id);
    emailObj1.Email_Subject__c='Test Sub';
    emailObj1.Email_Body__c='Test Body';
    emailObj1.Attachment__c=String.valueOf(attachment.Id);
    insert emailObj1;
    
    Apexpages.StandardController stdController = new Apexpages.StandardController(lead);  
    SingleEmailLeadcontroller controller= new   SingleEmailLeadcontroller(stdController);
    
    PageReference pageRef = Page.SendEmailOnOpportunity;
    pageRef.getParameters().put('id', String.valueOf(lead.Id));
    system.Test.setCurrentPage(pageRef);
    
       controller.lead=lead;
       controller.AttachmentId=attachment.Id;
       controller.emailSubject='test subject';
       controller.emailBody='test body';
       controller.strImageBlob='str';
       controller.renderPeronsal=true;
       controller.renderwork=true;
       controller.emailObj=emailObj1;
       controller.getItems();
       controller.contentType ='application/vnd.oasis.opendocument.text';
         
        
        controller.showEmail();
        controller.dosubmit();
       
    
    Test.StopTest();   
    }
    
    
    public static testMethod void testWorkEmail() {
    Test.StartTest();
    //create Lead
    Lead lead = New Lead();
    lead.Type__c='Retirement Plan';  
    insert lead;
    
    //Insert Attachment
    Attachment attachment =new Attachment();
    attachment.ParentId=lead.id;
    attachment.Name='dummy.txt';
    attachment.body=Blob.valueOf('Unit Test Attachment Body');
    insert attachment;
    
    
    //insert EmailTrackingObject
    Email_Tracking__c  emailObj1 = new Email_Tracking__c();
    emailObj1.Email_Type__c='Work Email';
    emailObj1.lead__c=lead.id;
    emailObj1.Attachment__c=String.valueOf(attachment.Id);
    emailObj1.Email_Subject__c='Test Sub';
    emailObj1.Email_Body__c='Test Body';
    emailObj1.Attachment__c=String.valueOf(attachment.Id);
    insert emailObj1;
    
    Apexpages.StandardController stdController = new Apexpages.StandardController(lead);  
    SingleEmailLeadcontroller controller= new   SingleEmailLeadcontroller(stdController);
    
    PageReference pageRef = Page.SendEmailOnOpportunity;
    pageRef.getParameters().put('id', String.valueOf(lead.Id));
    system.Test.setCurrentPage(pageRef);
    
       controller.lead=lead;
       controller.AttachmentId=attachment.Id;
       controller.emailSubject='test subject';
       controller.emailBody='test body';
       controller.strImageBlob='str';
       controller.renderPeronsal=true;
       controller.renderwork=true;
       controller.emailObj=new Email_Tracking__c();
       controller.emailObj.Email_Type__c='Work Email';
       controller.emailObj.lead__c=lead.id;
       controller.emailObj.Attachment__c=String.valueOf(attachment.Id);
       controller.emailObj.Email_Subject__c='Test Sub';
       controller.emailObj.Email_Body__c='Test Body';
       controller.emailObj.Attachment__c=String.valueOf(attachment.Id);
       
       
       controller.getItems();
       controller.contentType ='application/vnd.oasis.opendocument.text';
         
        
        controller.showEmail();
        //controller.sendEmail();
         controller.dosubmit();
         controller.upload();
    
    Test.StopTest();   
    }
    
    
     public static testMethod void testNoneEmail() {
    Test.StartTest();
    //create Lead
    Lead lead = New Lead();
    lead.Type__c='Retirement Plan';  
    insert lead;
    
    //Insert Attachment
    Attachment attachment =new Attachment();
    attachment.ParentId=lead.id;
    attachment.Name='dummy.txt';
    attachment.body=Blob.valueOf('Unit Test Attachment Body');
    insert attachment;
    
    
    //insert EmailTrackingObject
    Email_Tracking__c  emailObj1 = new Email_Tracking__c();
    emailObj1.Email_Type__c='Work Email';
    emailObj1.lead__c=lead.id;
    emailObj1.Attachment__c=String.valueOf(attachment.Id);
    emailObj1.Email_Subject__c='Test Sub';
    emailObj1.Email_Body__c='Test Body';
    emailObj1.Attachment__c=String.valueOf(attachment.Id);
    insert emailObj1;
    
    Apexpages.StandardController stdController = new Apexpages.StandardController(lead);  
    SingleEmailLeadcontroller controller= new   SingleEmailLeadcontroller(stdController);
    
    PageReference pageRef = Page.SendEmailOnOpportunity;
    pageRef.getParameters().put('id', String.valueOf(lead.Id));
    system.Test.setCurrentPage(pageRef);
    
      
       controller.AttachmentId=attachment.Id;
       controller.emailSubject='test subject';
       controller.emailBody='test body';
       controller.strImageBlob='str';
       controller.renderPeronsal=true;
       controller.renderwork=true;
       controller.emailObj= new Email_Tracking__c();
       controller.emailObj.Email_Type__c='Work Email';
       controller.emailObj.lead__c=lead.id;
       controller.emailObj.Attachment__c=String.valueOf(attachment.Id);
       controller.emailObj.Email_Subject__c='Test Sub';
       controller.emailObj.Email_Body__c='Test Body';
       controller.emailObj.Attachment__c=String.valueOf(attachment.Id);
       
        controller.lead=lead;
        controller.getItems();
        controller.contentType ='application/vnd.oasis.opendocument.text';
         
        
        controller.showEmail();
        controller.sendEmail();
         controller.dosubmit();
         controller.upload();
    
    Test.StopTest();   
    } */
    
    }