src/objects/Email_Tracking__c.object
<CustomObject>
    <description>This object is created to track emails on Opportunities</description>
    <fields>
        <fullName>Attachment__c</fullName>
        <description>This field is used to store the attachment id</description>
        <label>Attachment</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email_Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Message_Type__c</fullName>
        <label>Email Message Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single Email</fullName>
                </value>
                <value>
                    <fullName>Mass Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Status__c</fullName>
        <label>Email Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent Email</fullName>
                </value>
                <value>
                    <fullName>Replied Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Subject__c</fullName>
        <label>Email Subject</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReplyEmailContenetPdf__c</fullName>
        <label>ReplyEmailContenetPdf</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Email Trackings</relationshipLabel>
        <relationshipName>Email_Trackings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Email Tracking</label>
    <nameField>
        <displayFormat>ETOP-{0000}</displayFormat>
        <label>Email Tracking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ReplyEmailHandlerMassLead.cls
global class ReplyEmailHandlerMassLead implements Messaging.InboundEmailHandler {
    
    //Getting Inbound Email
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
    system.debug('inside ReplyEmailHandlerMassOpportunity ');
    Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
    Email_Tracking__c feedback= new Email_Tracking__c ();
    feedback.lead__c=[SELECT Id FROM Lead WHERE Email= :email.fromAddress or Official_Email__c=:email.fromAddress LIMIT 1].id;
    feedback.Email_Body__c =   email.plainTextBody;
    feedback.Email_Message_Type__c='Mass Email';
    feedback.Email_Status__c='Replied Email';
    feedback.Email_Subject__c=email.subject;
    system.debug('feedback.lead__c'+feedback.lead__c);
    try{
    blob b = blob.toPDF(email.plainTextBody);
     Attachment attachment = new Attachment();
              attachment.Name =''+system.now()+'.pdf';
              attachment.Body = b;
              attachment.ParentId = feedback.lead__c;
              insert attachment;
    feedback.ReplyEmailContenetPdf__c = attachment.id;
    }catch(Exception ex){}
   system.debug('email.textAttachments'+email.textAttachments) ;
    if(email.textAttachments != null){
        
            // Save attachments, if any
            for (Messaging.Inboundemail.TextAttachment tAttachment : email.textAttachments) {
              Attachment attachment = new Attachment();
             
              attachment.Name = tAttachment.fileName;
              attachment.Body = Blob.valueOf(tAttachment.body);
              attachment.ParentId = feedback.lead__c;
              insert attachment;
              feedback.Attachment__c=attachment.id;
              system.debug('feedback.Attachment__c'+feedback.Attachment__c);
            }
        }
        system.debug('email.binaryAttachments'+email.binaryAttachments) ;
          if(email.binaryAttachments != null){
        
            for (Messaging.Inboundemail.BinaryAttachment bAttachment : email.binaryAttachments) {
              Attachment attachment = new Attachment();
             
              attachment.Name = bAttachment.fileName;
              attachment.Body = bAttachment.body;
              attachment.ParentId = feedback.lead__c;
              insert attachment;
              feedback.Attachment__c=attachment.id;
              system.debug('feedback.Attachment__c'+feedback.Attachment__c);
            }
        }
    
    insert feedback;
    system.debug('feedback.Attachment__c'+feedback.Attachment__c);
    return result;
    
}
}