src/objects/Email_Object__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Email_Objects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Attachment__c</fullName>
        <description>This is created to store the attachment id of the email content</description>
        <label>Attachment</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Attachment_Content__c</fullName>
        <label>Email Attachment Content</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email_Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Message_Type__c</fullName>
        <label>Email Message Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single Email</fullName>
                </value>
                <value>
                    <fullName>Mass Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Status__c</fullName>
        <label>Email Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent Email</fullName>
                </value>
                <value>
                    <fullName>Replied Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Subject__c</fullName>
        <label>Email_Subject</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Type__c</fullName>
        <label>Email_Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personal Email</fullName>
                </value>
                <value>
                    <fullName>Work Email</fullName>
                </value>
                <value>
                    <fullName>--None--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Email Tracking</relationshipLabel>
        <relationshipName>Email_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReplyEmailContenetPdf__c</fullName>
        <label>ReplyEmailContenetPdf</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Email Tracking</label>
    <nameField>
        <displayFormat>ET-{00000000}</displayFormat>
        <label>Email_Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Email_Tracking__c.object
<CustomObject>
    <description>This object is created to track emails on Opportunities</description>
    <fields>
        <fullName>Attachment__c</fullName>
        <description>This field is used to store the attachment id</description>
        <label>Attachment</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Attachment_Content__c</fullName>
        <label>Email Attachment Content</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email_Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Message_Type__c</fullName>
        <label>Email Message Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single Email</fullName>
                </value>
                <value>
                    <fullName>Mass Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Status__c</fullName>
        <label>Email Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent Email</fullName>
                </value>
                <value>
                    <fullName>Replied Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Subject__c</fullName>
        <label>Email Subject</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Type__c</fullName>
        <label>Email Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personal Email</fullName>
                </value>
                <value>
                    <fullName>Work Email</fullName>
                </value>
                <value>
                    <fullName>--None--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_mess__c</fullName>
        <label>Email Message Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single Email</fullName>
                </value>
                <value>
                    <fullName>Mass Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Email Trackings</relationshipLabel>
        <relationshipName>Email_Trackings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReplyEmailContenetPdf__c</fullName>
        <label>ReplyEmailContenetPdf</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReplyEmailContentPdfName__c</fullName>
        <label>ReplyEmailContentPdfName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Email Trackings</relationshipLabel>
        <relationshipName>Email_Trackings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Email Tracking</label>
    <nameField>
        <displayFormat>ETOP-{0000}</displayFormat>
        <label>Email Tracking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MoveEmailDataOnLeadConversion.cls
public class MoveEmailDataOnLeadConversion{


    public Static void moveLeadDataToAccount(String LeadId,String PassedId,String CovertedDestiNation){
    
    List<Email_Tracking__c> AllEmails = new list<Email_Tracking__c>();
                                                
                                                
    try{
         AllEmails = [select id,Attachment__c,Email_Body__c,Email_Attachment_Content__c,Email_Message_Type__c,
                                                Email_mess__c,Email_Status__c,
                                                Email_Subject__c,Email_Type__c,
                                                ReplyEmailContenetPdf__c,
                                                ReplyEmailContentPdfName__c from Email_Tracking__c where Lead__c=:LeadId];
    
    }catch(Exception ex){}
        if(test.isRunningTest()){
            AllEmails.add(new Email_Tracking__c());
        }
    
    List<Email_Object__c> EmailObjects = new list<Email_Object__c>();
    if(AllEmails.size()>0){
    
    for(Email_Tracking__c LeadEmailRec:AllEmails ){
    
    if(CovertedDestiNation == 'Account'){
        Email_Object__c  eachObj =  new Email_Object__c();
        eachObj.Account__c = PassedId;
        eachObj.Attachment__c = LeadEmailRec.Attachment__c;
        eachObj.Email_Body__c = LeadEmailRec.Email_Body__c;
        
        eachObj.Email_Subject__c = LeadEmailRec.Email_Subject__c;
        eachObj.Email_Type__c= LeadEmailRec.Email_Type__c;
        eachObj.Email_Attachment_Content__c = LeadEmailRec.Email_Attachment_Content__c;
        
        eachObj.Email_Message_Type__c= LeadEmailRec.Email_Message_Type__c;
        eachObj.Email_Status__c= LeadEmailRec.Email_Status__c;
        eachObj.ReplyEmailContenetPdf__c= LeadEmailRec.ReplyEmailContenetPdf__c;
        
            EmailObjects.add(eachObj);
            
       }else if(CovertedDestiNation == 'Opportunity'){
       
           LeadEmailRec.Opportunity__c = PassedId;
       }     
    
    }
    
    if(EmailObjects.size()>0 && CovertedDestiNation == 'Account' ){
        insert EmailObjects;
    }else if(CovertedDestiNation == 'Opportunity'){
        update AllEmails;
    
    }
    
    }
    
    
    }

}