src/objects/Meeting_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>This field is used to track the Agenda of the appointment</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Type__c</fullName>
        <label>Email Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Personal Email</fullName>
                </value>
                <value>
                    <fullName>Work Email</fullName>
                </value>
                <value>
                    <fullName>--None--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>This is used to track the End Date Time of the appointment</description>
        <label>End Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Meeting_Invite_Status__c</fullName>
        <label>Meeting Invite Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This  is used to track the meeting invites on Opportunity object</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Meeting Trackings</relationshipLabel>
        <relationshipName>Meeting_Trackings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>to track the start date time of the meeting</description>
        <label>Start Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>This is used to capture meeting Subject</description>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Meeting Tracking</label>
    <nameField>
        <label>Meeting  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityMeetingResponseHandler.cls
global class OpportunityMeetingResponseHandler implements Messaging.InboundEmailHandler {


    //Getting Inbound Email
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
    system.debug('>>>>> '+email.fromAddress);
    Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
    Meeting_Tracking__c feedback= new Meeting_Tracking__c();
    feedback.Opportunity__c =[SELECT Id FROM opportunity WHERE Work_Email__c= :email.fromAddress OR Personal_Email__c= :email.fromAddress    LIMIT 1].id;
    feedback.Description__c =   email.plainTextBody;
    //feedback.Email_Message_Type__c='Mass Email';
    String emailBody = email.plainTextBody.toLowercase();
    String status;
    if(emailBody.contains('yes')){
        status = 'Accepted';
    }else{
            status = 'Rejected';
    
    }
    feedback.Start_Date_Time__c = system.today();
    feedback.End_Date_Time__c = system.today();
    feedback.Email_Type__c = 'Personal Email';
    feedback.Meeting_Invite_Status__c= status;
    feedback.Subject__c=email.subject;
    
    
    insert feedback;
    return result;
    
}




}